# Generated by cucumber-sinatra. (2014-06-01 10:47:12 +0100)

ENV['RACK_ENV'] = 'test'
ENV['MAILCHIMP_API_KEY'] = 'ABC'
ENV['MAILCHIMP_LIST_NAME'] = 'ABC'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')
set :views, File.join(File.dirname(__FILE__), '..', '..', 'views')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Sinatra::Application

class ProximitusWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ProximitusWorld.new
end
